### ISSUE TITLE
released code

### ISSUE THREAD

**Issue by JaniceXiong** [tencent-ailab/Lodoss#1]
Hi, thanks for your inspiring work! Could I ask whether you will upload the code and implementation details recently? Thanks a lot!

**Comment by dennlinger** [comment]
Seconded! It's a real bummer reading through the paper and then realizing that the provided link doesn't have any content...

**Comment by KaiQiangSong** [comment]
> Hi, thanks for your inspiring work! Could I ask whether you will upload the code and implementation details recently? Thanks a lot!

> Seconded! It's a real bummer reading through the paper and then realizing that the provided link doesn't have any content...

Hi JaniceXiong and dennlinger,

We thank you for your questions and interest in our project. We will keep our promise for the code release. We are undergoing the code release process right now. It may take a while, we are doing our best on that. I really understand you want to get the released code ASAP, please give us some time. 

Please feel free to leave your email address, we will send you an email notification once the code is ready.
